version: '3.7'
services:

  # cadvisor:
  #   container_name: cadvisor
  #   image: gcr.io/cadvisor/cadvisor:v0.39.0
  #   restart: always
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro

  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    volumes:
      - ./logs:/var/log
      - ./conf/vector.yaml:/etc/vector/vector.yaml

  fluentd:
    image: fluent/fluentd:v1.16-2
    container_name: fluentd
    volumes:
      - ./logs:/var/log
      - ./conf/fluentd.conf:/conf/fluentd.conf
    command: -c /conf/fluentd.conf

  fluent-bit:
    image: fluent/fluent-bit:3.1.6
    container_name: fluent-bit
    volumes:
      - ./logs:/var/log
      - ./conf/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  logstash:
    image: logstash:8.15.0
    container_name: logstash
    volumes:
      - ./logs:/var/log
      - ./conf/logstash.conf:/conf/logstash.conf
    command: logstash -f /conf/logstash.conf

  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:latest
    ports:
      - "9095:9095"
    volumes:
      - ./kafka-data:/bitnami/kafka
    environment:
      # KRaft settings
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners ref: https://stackoverflow.com/questions/75680387/access-bitnami-kafka-docker-container-from-everywhere
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://localhost:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes